# See: https://crate-ci.github.io/azure-pipelines/setup.html

jobs:
 - template: default.yml@templates
   parameters:
      setup:
        # libasound2-dev: required by alsa-sys <- cpal <- ttspico/examples/hello.rs
        - script: sudo apt install libasound2-dev
          condition: eq(variables['Agent.OS'], 'Linux')
          displayName: Install libasound2-dev

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: GitHub
