[package]
name = "ttspico"
version = "0.1.0"
edition = "2018"

authors = ["Paolo Jovon <paolo.jovon@gmail.com>"]
readme = "../README.md"
description = """
High-level bindings to the Pico TTS engine.
(includes patches for x86_64 support)
"""
categories = ["api-bindings", "multimedia::audio", "text-processing"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttspico-sys = { path = "../ttspico-sys", version = "^0.1" }

[dev-dependencies]
cpal = "^0.10" # (for examples/hello.rs)
