[package]
name = "ttspico"
version = "0.1.0"
authors = ["Paolo Jovon <paolo.jovon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttspico-sys = { path = "../ttspico-sys", version = "^0.1" }